### ISSUE TITLE
Update the graphs in the two-page paper

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/GECCO-2017-ancestry-poster#8]
We don't have room for many graphs in the two-page poster paper, so we need to take some care in deciding which graphs we want to include. We also need to make sure we're happy with the color scheme used for those graphs; my inclination would be to go with the the autoencoding color schemes, but I'm open to alternate ideas.

Things we need to do:

* [x] Decide which graphs to include
* [ ] Decide on a coloring scheme
* [ ] Build the graphs and incorporate them into the paper
* [ ] Trim unsuccessful graph to 150-200 generations

**Comment by casal033** [comment]
Sounds great! I'm a bit busy today/tomorrow. I'll take a look at this on Sunday (:

**Comment by NicMcPhee** [comment]
Based on e-mail discussions, I think we'll keep these two graphs (so focus on successful vs. unsuccessful as the major comparison point), but trim the unsuccessful graph to something like 150 to 200 generations so it's not so long and we can get this thing down to 2 pages.
